filebeat.inputs:
  - type: filestream
    id: python-obs-json
    enabled: true
    paths:
      - /logs/**/*.log
    parsers:
      - ndjson:
          overwrite_keys: true
          add_error_key: true
          expand_keys: true

processors:
  - add_fields:
      target: ''
      fields:
        app: ${APP_NAME:obs-ws-server}
        environment: ${ENV:dev}
  - rename:
      fields:
        - from: level
          to: log.level
        - from: logger
          to: log.logger
      ignore_missing: true
      fail_on_error: false
  - copy_fields:
      fields:
        - from: func
          to: event.action
      fail_on_error: false
      ignore_missing: true

setup.template.enabled: true
# 강제로 인덱스 템플릿 모드로 사용 (데이터스트림과 충돌 방지)
setup.template.type: index
setup.template.name: "python-obs-control"
setup.template.pattern: "python-obs-control-*"
setup.ilm.enabled: false
setup.kibana:
  host: "http://kibana:5601"
setup.dashboards.enabled: false

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "python-obs-control-%{[environment]:dev}-%{+yyyy.MM.dd}"

logging.level: debug
logging.selectors: ["*"]
logging.to_files: false
logging.to_stderr: true
