version: "3.9"
services:
  obs-control:
    build: .
    image: obs-control:local
    container_name: obs-control
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      # Map to pydantic settings via env vars
      - HOST=0.0.0.0
      - PORT=8080
      - LOG_LEVEL=info
      - OBS_HOST=host.docker.internal
      - OBS_PORT=4455
      - OBS_PASSWORD=
      - OBS_SKIP_AUTOSTART_IN_DOCKER=1
      - AUTO_BOOTSTRAP=1
      - SCREENSHOT_DIR=/data/screenshots
    volumes:
      - ./config:/app/config:rw
      - ./logs:/app/logs:rw
      - ./data/screenshots:/data/screenshots:rw
    # default command uses uvicorn (see Dockerfile)

  # Optional: auto-update running container when a new image is pushed
  # Requires image hosted in a registry and tags being updated
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 obs-control


