version: "3.9"
services:
  obs-control-git:
    build: .
    image: obs-control:git
    container_name: obs-control-git
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - REPO_URL=https://github.com/64etuor/python-obs-control.git
      - REPO_BRANCH=main
      - APP_MODULE=app.presentation.app_factory:app
      - OBS_HOST=host.docker.internal
      - OBS_PORT=4455
      - OBS_SKIP_AUTOSTART_IN_DOCKER=1
      - SCREENSHOT_DIR=/data/screenshots
    volumes:
      - ./config:/app/config:rw
      - ./logs:/app/logs:rw
      - ./data/screenshots:/data/screenshots:rw
    entrypoint: ["/usr/local/bin/entrypoint-git.sh"]

