services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.13.4
    user: root
    command: ["--strict.perms=false"]
    env_file:
      - ../.env
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ../logs:/logs:ro
      - filebeatdata:/usr/share/filebeat/data
    depends_on:
      - elasticsearch
      - kibana
    restart: unless-stopped

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:8.13.4
    user: root
    command: ["--strict.perms=false"]
    env_file:
      - ../.env
    volumes:
      - ./metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - metricbeatdata:/usr/share/metricbeat/data
    depends_on:
      - elasticsearch

volumes:
  esdata:
  filebeatdata:
  metricbeatdata:
